version: '3.8'

volumes:
  db-data:

services:
  postgres:
    container_name: todo-db
    image: postgres:14.2-alpine
    restart: always
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=50'
      - '-c'
      - 'shared_buffers=1GB'
      - '-c'
      - 'effective_cache_size=4GB'
      - '-c'
      - 'work_mem=16MB'
      - '-c'
      - 'maintenance_work_mem=512MB'
      - '-c'
      - 'random_page_cost=1.1'
      - '-c'
      - 'temp_file_limit=10GB'
      - '-c'
      - 'log_min_duration_statement=200ms'
      - '-c'
      - 'idle_in_transaction_session_timeout=10s'
      - '-c'
      - 'lock_timeout=1s'
      - '-c'
      - 'statement_timeout=60s'
      - '-c'
      - 'shared_preload_libraries=pg_stat_statements'
      - '-c'
      - 'pg_stat_statements.max=10000'
      - '-c'
      - 'pg_stat_statements.track=all'
    environment:
      POSTGRES_DB: $PG_NAME
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASS
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./sql:/docker-entrypoint-initdb.d
    ports:
      - $PG_PORT:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $PG_USER -d $PG_NAME']
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  app:
    container_name: todo-app
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    ports:
      - $APP_PORT:$APP_PORT
