FROM node:16.15-alpine as dependencies
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile
COPY . .

FROM dependencies as builder
RUN yarn build

FROM node:16.15-alpine as production
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.env ./.env
COPY --from=builder /app/build ./

CMD ["node", "./build/server.js"]
